### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by glouw** [tinwe6/loxi#3]
Well done. 

Do you have any examples on how Lox is used? I'm keen on its syntax.

**Comment by tinwe6** [comment]
Thanks glouw. The Lox language is fully described [here](http://www.craftinginterpreters.com/the-lox-language.html)

If you want to read a Lox program, @benhoyt wrote a Lox interpreter in... Lox, [LoxLox](https://github.com/benhoyt/loxlox). It's the only non-trivial program written in Lox that I know of!

You can also look at the Lox snippets that are used to test the interpreter: (https://github.com/munificent/craftinginterpreters/tree/master/test)

Hope this helps!
